### ISSUE TITLE
Required 'annotations' directory not created when upgrade from Detrius (using upgrade plugin)

### ISSUE THREAD

**Issue by rswindell** [splitbrain/dokuwiki-plugin-upgrade#163]
After upgrading using the 'upgrade' plugin to upgrade from "Detritus" to Release 2018-04-22a "Greebo", I got the follow error when accessing the wiki. This error was resolved by manually creating the empty directory data/pages/annotations ('mkdir data/pages/annotations'):

PHP message: PHP Fatal error: Uncaught exception 'UnexpectedValueException' with message 'DirectoryIterator::__construct(/var/www/html/wiki.synchro.net/data/pages/annotations): failed to open dir: No such file or directory' in /var/www/html/wiki/lib/plugins/userannotations/action.php:72 Stack trace: #0 /var/www/html/wiki/lib/plugins/userannotations/action.php(72): DirectoryIterator->__construct('/var/www/html/w...') #1 /var/www/html/wiki/inc/events.php(229): action_plugin_userannotations->_displayAnnotations(Object(Doku_Event), NULL) #2 /var/www/html/wiki/inc/events.php(79): Doku_Event_Handler->process_event(Object(Doku_Event), 'AFTER') #3 /var/www/html/wiki/inc/events.php(115): Doku_Event->advise_after() #4 /var/www/html/wiki/inc/events.php(256): Doku_Event->trigger('tpl_content_cor...', true) #5 /var/www/html/wiki/inc/template.php(83): trigger_event('TPL_ACT_RENDER', 'show', 'tpl_content_cor...') #6 /var/www/html/wiki/lib/tpl/monobook/main.php(662): tpl_content(true) #7 /var/www/html/wiki/inc/actions.p...

**Comment by rswindell** [comment]
I think this was due to an old/unused 'annotations plugin' I had installed. Removing issue.
